[package]
name = "rstrain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
regex = "1"
fxhash = "0.2.1"
clap = "2.34.0"
prettytable-rs = "^0.8"